### ISSUE TITLE
 /bin/bash^M: bad interpreter:

### ISSUE THREAD

**Issue by thanhson1085** [apolloclark/vagrant-jenkins-pipeline#2]
I got a error when I ran `vagrant up`

```
==> default: INFO: Done installing Python.
==> default: INFO: Installing Jenkins plugins...
==> default: /tmp/vagrant-shell: /vagrant/jenkins_install_plugins.sh: /bin/bash^M: bad interpreter: No such f                                        ile or directory
==> default:  * Restarting Jenkins Continuous Integration Server jenkins
==> default:    ...done.
```

I am using Win 10, Git Bash and Vagrant + Virtualbox

**Comment by thanhson1085** [comment]
You used a Editor on Window to create the scripts?

I solved the issue by using `vi` to recreate the scripts

**Comment by apolloclark** [comment]
Yes, I used Eclipse on Ubuntu. I'm guessing it's an issue with Windows \n\r line endings, I've seen this under Windows 7 before. By default Git will clone files, using your system default line-endings, but this doesn't work correctly when the provisioning script is then run inside a Linux guest VM. 

I'll add a .gitattributes file to the project to fix this for Windows users. Thanks for reporting! :)
