### ISSUE TITLE
Jenkins User / Password

### ISSUE THREAD

**Issue by tkleiber** [apolloclark/vagrant-jenkins-pipeline#3]
Hi!

I have started via virtualbox.

Jenkins ask for user and password, I did not find this information in the documentation here?

Kind regards
Torsten

**Comment by apolloclark** [comment]
Huh weird... I thought it would install without a password. Anyways, I explicitly disabled the security check, for now. Do a git pull for the update.

**Comment by tkleiber** [comment]
Unfortunatly no change. I test this local on windows with Virtualbox.

**Comment by apolloclark** [comment]
Ok, yes, the security changes to disable login did not also include changes to allow running scripts. I'll fix this over the weekend. Thanks for the info! :)
